### ISSUE TITLE
Please remove ineffective registration of resolver

### ISSUE THREAD

**Issue by Chris2011** [ceylon/ceylon-ide-netbeans#2]
I get a warning, while opening NetBeans:

`WARNING [org.netbeans.modules.openide.filesystems.declmime.MIMEResolverImpl]: Ineffective registration of resolver Services/MIMEResolver/CeylonResolver.xml use @MIMEResolver.Registration! See bug #191777.`

please change it with a better solution.

Regards

Chris

**Comment by bjansen** [comment]
Thanks for all the reports! I believe you're one of the first persons to test this plugin (other than me), that might explain why a few things are broken outside of my dev environment ;)

**Comment by bjansen** [comment]
I was already using `@MIMEResolver.Registration`, but forgot to remove the old XML layer :)
