### ISSUE TITLE
OutOfBoundsException while opening NetBeans

### ISSUE THREAD

**Issue by Chris2011** [ceylon/ceylon-ide-netbeans#3]
When I open NetBeans und and I have a look into the messages.log, I see this exception:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967)
	at com.redhat.ceylon.ide.netbeans.PluginStartup.registerCeylonModules(PluginStartup.java:245)
	at com.redhat.ceylon.ide.netbeans.PluginStartup.run(PluginStartup.java:75)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
```

**Comment by bjansen** [comment]
I think I know how to fix this, but just to confirm my analysis: could you open the folder where NetBeans extracts plugins and tell me if there's a subfolder in `modules/ext` that contains a JAR that has no version in its file name?

Something like `.../modules/ext/somefolder/somefile.jar`.

On macOS, plugins are extracted in `<user home>/Library/Application Support/NetBeans/8.2/`. See [this page](http://wiki.netbeans.org/FaqLogMessagesFile) for other OS.

**Comment by Chris2011** [comment]
Which jar do you mean? So it still happens with 1.3.4. I have some ceylon jars in the ext folder but with version. There is a car file called: com.redhat.ceylon.ide.netbeans-current.car

**Comment by Chris2011** [comment]
The link is for finding the messages.log and I know this, because I used it while opening NetBeans.

**Comment by bjansen** [comment]
I mean any jar that would come from another plugin you installed.

**Comment by Chris2011** [comment]
I will check it later, thx.
