### ISSUE TITLE
Error when saving a ".ceylon" file

### ISSUE THREAD

**Issue by negora** [ceylon/ceylon-ide-netbeans#8]
Hello:

I'm using the build 1.3.4.1709230046.25.8 with NetBeans IDE 8.2, in Debian 9.1. I've created a new project. Whenever I save the changes in a file with `.ceylon` extension, a new exception is thrown. It doesn't matter if it's `module.ceylon`, `package.ceylon` or a file with code in it.

I've attached the exception's stack trace. A summary:

`com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve com.redhat.ceylon.compiler.typechecker.analyzer.Warning` .

Thank you.
[exception.log](https://github.com/ceylon/ceylon-ide-netbeans/files/1327495/exception.log)

**Comment by bjansen** [comment]
I believe it's related to what I fixed in #4, could you download and install the build 1.3.4.1709241836.25.8 and tell me if it fixed the problem please?

**Comment by negora** [comment]
Hello Bastien:

Yes, you're right. The new version has not only fixed my problem, but has also added some elements that didn't appear before in the "Projects" panel. Even the syntax colouring works fine now (I was having some issues).

Thanks for such a fast response and also for making this plug-in possible. I hope this plug-in gets far :) . I've started to use Eclipse, but I'm having some problems with it. It would be fantastic if I could continue using NetBeans for my Ceylon development.

**Comment by bjansen** [comment]
Great, I'll close the issue then.
